export const ProductCategories: {
  flipkart: string[][]
  amazon: string[][]
  myntra: string[][]
  shopsy: string[][]
  dmart: string[][]
} = {
  flipkart: [
    ["1", "clothing & accessories"],
    ["2", "food & nutrition"],
    ["3", "kitchen cookware & serveware"],
    ["4", "edible oil"],
    ["5", "health & beauty"],
    ["6", "footwear"],
    ["7", "painting & posters"],
    ["8", "artificial jewelry"],
    ["9", "soap"],
    ["10", "cosmetic"],
    ["11", "health & wellness"],
    ["12", "clothing & apparels"],
    ["13", "home & kitchen"],
    ["14", "other"],
  ],
  amazon: [
    ["1", "amazon device accessories"],
    ["2", "automotive and powersports"],
    ["3", "baby products"],
    ["4", "backpacks and handbags"],
    ["5", "beauty, health, and personal care"],
    ["6", "books"],
    ["7", "business, industrial, and scientific supplies"],
    ["8", "baby products, toys & education"],
    ["9", "music, movies, video games, entertainment"],
    ["10", "industrial, medical, scientific supplies & office products"],
    ["11", "clothing, fashion, fashion accessories, jewellery, luggage, shoes"],
    ["12", "electronics (camera, mobile, pc, wireless) & accessories"],
    ["13", "grocery, food & pet supplies"],
    ["14", "health, beauty, personal care & personal care appliances"],
    ["15", "personal care appliances"],
    ["16", "home, décor, home improvement, furniture, outdoor"],
    ["17", "lawn & garden"],
    ["18", "kitchen, large & small appliance"],
    ["19", "sports, gym & sporting equipment"],
    ["20", "other"],
  ],
  myntra: [
    ["1", "clothing & accessories"],
    ["2", "food & nutrition"],
    ["3", "kitchen cookware & serveware"],
    ["4", "edible oil"],
    ["5", "health & beauty"],
    ["6", "footwear"],
    ["7", "painting & posters"],
    ["8", "artificial jewelry"],
    ["9", "soap"],
    ["10", "cosmetic"],
    ["11", "health & wellness"],
    ["12", "clothing & apparels"],
    ["13", "home & kitchen"],
    ["14", "other"],
  ],
  shopsy: [[]],
  dmart: [[]],
}
