export const jobs = [
  {
    job_id: "unique job identifier",
    title: "Digital Marketing",
    location: "job location",
    employment_type: "Full Time",
    description: "job description",
    requirements: "job requirements or qualifications",
    posted_date: "date when the job was posted",
    expiry_date: "date when the job posting expires",
    contact_name: "name of the contact person",
    contact_email: "email address of the contact person",
    contact_phone: "phone number of the contact person",
    tags: "product",
    is_active: "true or false indicating if the job is currently active/open",
    applicants: ["list", "of", "applicant", "user_ids"],
    created_at: "timestamp of when the job posting was created",
    updated_at: "timestamp of when the job posting was last updated",
  },
  {
    job_id: "unique job identifier",
    title: "job title",
    location: "job location",
    employment_type: "full-time, part-time, contract, etc.",
    description: "job description",
    requirements: "job requirements or qualifications",
    posted_date: "date when the job was posted",
    expiry_date: "date when the job posting expires",
    contact_name: "name of the contact person",
    contact_email: "email address of the contact person",
    contact_phone: "phone number of the contact person",
    tags: "product",
    is_active: "true or false indicating if the job is currently active/open",
    applicants: ["list", "of", "applicant", "user_ids"],
    created_at: "timestamp of when the job posting was created",
    updated_at: "timestamp of when the job posting was last updated",
  },
  {
    job_id: "unique job identifier",
    title: "job title",
    location: "job location",
    employment_type: "full-time, part-time, contract, etc.",
    description: "job description",
    requirements: "job requirements or qualifications",
    posted_date: "date when the job was posted",
    expiry_date: "date when the job posting expires",
    contact_name: "name of the contact person",
    contact_email: "email address of the contact person",
    contact_phone: "phone number of the contact person",
    tags: "product",
    is_active: "true or false indicating if the job is currently active/open",
    applicants: ["list", "of", "applicant", "user_ids"],
    created_at: "timestamp of when the job posting was created",
    updated_at: "timestamp of when the job posting was last updated",
  },
]
