import { ColumnType } from "@/lib/types"

export const Columns: ColumnType = {
  flipkart: {
    shippingFee: "Shipping Fees",
    collectionFee: "Collection Fees",
    commissionRate: "Commission Fees",
    fixedFee: "Fixed Fees",
    gst: "GST on Marketplace Fees",
    totalPlateformFee: "Total Flipkart Fees",
    netMargin: "Settlement Amount",
    netMarginPercentage: "Net Margin %",
  },
  amazon: {
    commissionRate: "Referral Fees",
    fixedFee: "Closing Fees",
    shippingFee: "Shipping Fees",
    collectionFee: "Other Fees",
    gst: "GST on Marketplace Fees",
    totalPlateformFee: "Total Amazon Fees",
    netMargin: "Settlement Amount",
    netMarginPercentage: "Net Margin %",
  },
  myntra: {
    sellingPrice: "Selling Price",
    discount: "Discount",
    overallGST: "Overall GST",
    GMV: "GMV",
    shipmentFee: "Shipping Fees",
    fixedFees: "Fixed Fees",
    commissionRate: "Marketplace Fees",
    totalPlateformFee: "Total Myntra Fees",
    netAmountToPay: "Settlement Amount",
    netMarginPercentage: "Net Margin %",
  },
  ajio: {
    sellingPrice: "Selling Price",
    discount: "Discount",
    overallGst: "Overall GST",
    forwardShipmentCost: "Forward Shipment Cost",
    backwardShipmentCost: "Backward Shipment Cost",
    marketPlaceFee: "Marketplace Fees",
    gstReburshment: "GST Reburshment",
    totalAjoFees: "Total Ajio Fees",
    netAmountToPay: "Net Amount To Pay",
    netMarginPercentage: "Net Margin %",
  },
  shopsy: {
    shippingFee: "Shipping Fees",
    collectionFee: "Collection Fees",
    commissionRate: "Commission Fees",
    fixedFee: "Fixed Fees",
    gst: "GST on Marketplace Fees",
    totalPlateformFee: "Total Flipkart Fees",
    netMargin: "Settlement Amount",
    netMarginPercentage: "Net Margin %",
  },
}
